### ISSUE TITLE
[Epic - Tree Sources] All Trees in database from sources

### ISSUE THREAD

**Issue by zoobot** [waterthetrees/wtt_server#139]
1. Iterate through the sources table rows
2. Save trees to the treedata table

Note: make sure when all these trees are created, we set created/modified date so that all the geojson trees don't show up on the map as doubles of the vector tiles. Possibly just turn off created and set modified back in time for this query.
https://github.com/waterthetrees/wtt_server/blob/main/server/routes/treemap/treemap-queries.js#L23

### Milestone 0 - Design / Planning
- [x] #142
- [ ] [Tree Sources - Design] Table Modify View
- [ ] [Tree Sources - Design] Sticky Search
- [ ] #143
- [ ] #144
- [ ] [Tree Sources - Design] Confirmation Screen once uploaded source data
- [ ] [Tree Sources - Design] Section Be notified to update data
- [ ] [Tree Sources - Design] Notify User to know if data they "manage" was modified

### Milestone 1 -

**Comment by zoobot** [comment]
@tzinckgraf Do you have all the world trees in the db for the stuff you've been doing with clustering?

I am wanting this for tree-taxonomy stuff I am doing.
